controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      
    hand_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

arm_velocity_controller:
  ros__parameters:
    joints:
      - rotation1
      - rotation2
      - rotation3
      - rotation4
      # - rotation5

hand_velocity_controller:
  ros__parameters:
    joints:
      - slide1
      - slide2
