teleop_node:
  ros__parameters:
    joy_teleop:
      arm_teleop:
        type: topic
        interface_type: std_msgs/msg/Float64MultiArray
        topic_name: /arm_velocity_controller/commands
        deadman_buttons: [4]
        axis_mappings:
          - axis: 0
            target: data.0
            scale: 1.0
          - axis: 1
            target: data.1
            scale: 1.0
          - axis: 3
            target: data.2
            scale: 1.0
          - axis: 4
            target: data.3
            scale: 1.0
          - axis: 6
            target: data.4
            scale: 1.0

      hand_teleop:
        type: topic
        interface_type: std_msgs/msg/Float64MultiArray
        topic_name: /hand_velocity_controller/commands
        deadman_buttons: [5]
        axis_mappings:
          - axis: 2
            target: data.0
            scale: 0.1
          - axis: 5
            target: data.1
            scale: 0.1