# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - aurora_arm_controller

  aurora_arm_controller:
    type: FollowJointTrajectory
    joints:
      - body_spin_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
    action_ns: follow_joint_trajectory
    default: true