# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    aurora_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

aurora_arm_controller:
  ros__parameters:
    joints:
      - body_spin_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity